from(bucket:"stations")
  |> range(start: -24h)
  |> filter(fn: (r) => r._measurement == "weather_station")
  |> filter(fn: (r) => r._field == "temperature")
  |> sort(columns: ["_time"], desc: true)
  |> limit(n: 5)